#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CHANGE_DIR = ROOT / "docs" / "ai" / "changes" / "geometry-full2d-v0_6"
DEFAULT_RELEASE_REPORT = CHANGE_DIR / "evidence" / "release_acceptance_report.json"
DEFAULT_CLOSURE = CHANGE_DIR / "CLOSURE.md"
CLAIM = "V0.6_GEOMETRY_FULL2D_EXECUTION_LOCKED_REAL_SOLVER_CAUSAL_FULL_PIPELINE_READY"
GENERATOR_MARKER = "Generated by scripts/check_release_acceptance_v0_6.py"
FORBIDDEN_CLAIMS = (
    "SOURCE_FAITHFUL",
    "ACCEPTANCE_COMPLETE",
    "PRODUCTION_SAFE",
    "R-ID VERIFIED",
    "open problem solving ready",
    "open-problem-solving ready",
    "full pipeline completed",
    "high-performance geometry prover",
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Enforce v0.6 closure claim ceiling from release report.")
    parser.add_argument("--release-report", type=Path, default=DEFAULT_RELEASE_REPORT)
    parser.add_argument("--closure", type=Path, default=DEFAULT_CLOSURE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    report = check_closure_claim_ceiling(resolve(args.release_report), resolve(args.closure))
    if args.output:
        output = resolve(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["status"] == "passed" else 1


def check_closure_claim_ceiling(release_report_path: Path, closure_path: Path) -> dict[str, Any]:
    errors: list[str] = []
    release_report: dict[str, Any] | None = None
    if not release_report_path.exists():
        errors.append("release_report_missing")
    else:
        try:
            parsed = json.loads(release_report_path.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                release_report = parsed
            else:
                errors.append("release_report_not_object")
        except Exception as exc:
            errors.append(f"release_report_unreadable:{exc}")

    if release_report is not None:
        errors.extend(validate_release_report(release_report))

    closure_text = ""
    if not closure_path.exists():
        errors.append("closure_missing")
    else:
        closure_text = closure_path.read_text(encoding="utf-8")
        errors.extend(validate_closure_text(closure_text, release_report_path))

    forbidden_present = [claim for claim in FORBIDDEN_CLAIMS if claim.lower() in closure_text.lower()]
    if forbidden_present:
        errors.append("closure_forbidden_claims_present")

    return {
        "schema_version": "ClosureClaimCeilingCheckV06",
        "checker_name": "check_closure_claim_ceiling_v0_6.py",
        "status": "passed" if not errors else "failed",
        "errors": sorted(set(errors)),
        "release_report": str(release_report_path),
        "closure": str(closure_path),
        "allowed_claim": CLAIM,
        "forbidden_claims_present": forbidden_present,
        "release_report_file_ref": file_sha256(release_report_path) if release_report_path.exists() else None,
        "release_report_core_ref": release_report.get("release_report_core_ref") if isinstance(release_report, dict) else None,
    }


def validate_release_report(report: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if report.get("status") != "passed":
        errors.append("release_report_status_not_passed")
    if report.get("closure_allowed") is not True:
        errors.append("release_report_closure_not_allowed")
    if report.get("claim_ceiling") != CLAIM:
        errors.append("release_report_claim_ceiling_mismatch")
    for field in ("hard_blockers", "release_blockers", "work_debt_open"):
        value = report.get(field)
        if value != []:
            errors.append(f"release_report_{field}_not_empty")
    expected_core_ref = release_report_core_ref(report)
    if report.get("release_report_core_ref") != expected_core_ref:
        errors.append("release_report_core_ref_mismatch")
    return errors


def validate_closure_text(text: str, release_report_path: Path) -> list[str]:
    errors: list[str] = []
    if GENERATOR_MARKER not in text:
        errors.append("closure_not_generated_by_release_checker")
    if CLAIM not in text:
        errors.append("closure_missing_exact_claim_ceiling")
    release_report_rel = rel_or_abs(release_report_path)
    if release_report_rel not in text and str(release_report_path) not in text:
        errors.append("closure_missing_release_report_path")
    expected_ref = None
    if release_report_path.exists():
        try:
            parsed = json.loads(release_report_path.read_text(encoding="utf-8"))
            if isinstance(parsed, dict):
                expected_ref = parsed.get("release_report_core_ref") or release_report_core_ref(parsed)
        except Exception:
            expected_ref = None
    if expected_ref and expected_ref not in text:
        errors.append("closure_missing_release_report_core_ref")
    if "Manual closure" in text or "manually generated" in text.lower():
        errors.append("closure_mentions_manual_generation")
    return errors


def resolve(path: Path) -> Path:
    return path if path.is_absolute() else ROOT / path


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def release_report_core_ref(report: dict[str, Any]) -> str:
    core = json.loads(json.dumps(report))
    core.pop("release_report_core_ref", None)
    core["duration_seconds"] = "omitted_for_release_report_core_ref"
    core["generated_at"] = "omitted_for_release_report_core_ref"
    core["closure_claim_ceiling_summary"] = {"omitted_for_release_report_core_ref": True}
    required = core.get("required_results")
    if isinstance(required, dict):
        required.pop("closure_claim_ceiling", None)
    encoded = json.dumps(core, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def rel_or_abs(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
